# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1016, 670)
        MainWindow.setMinimumSize(QtCore.QSize(1016, 670))
        MainWindow.setMaximumSize(QtCore.QSize(1016, 670))
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setMaximumSize(QtCore.QSize(1016, 644))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.user_info_label = QtGui.QLabel(self.centralWidget)
        self.user_info_label.setGeometry(QtCore.QRect(25, 20, 171, 28))
        self.user_info_label.setMinimumSize(QtCore.QSize(128, 16))
        self.user_info_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.user_info_label.setFont(font)
        self.user_info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_info_label.setWordWrap(False)
        self.user_info_label.setObjectName(_fromUtf8("user_info_label"))
        self.name_label = QtGui.QLabel(self.centralWidget)
        self.name_label.setGeometry(QtCore.QRect(26, 50, 75, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setMinimumSize(QtCore.QSize(70, 16))
        self.name_label.setMaximumSize(QtCore.QSize(200, 200))
        self.name_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.lat_label = QtGui.QLabel(self.centralWidget)
        self.lat_label.setGeometry(QtCore.QRect(26, 85, 64, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lat_label.sizePolicy().hasHeightForWidth())
        self.lat_label.setSizePolicy(sizePolicy)
        self.lat_label.setMinimumSize(QtCore.QSize(57, 16))
        self.lat_label.setMaximumSize(QtCore.QSize(200, 200))
        self.lat_label.setObjectName(_fromUtf8("lat_label"))
        self.long_label = QtGui.QLabel(self.centralWidget)
        self.long_label.setGeometry(QtCore.QRect(26, 120, 72, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.long_label.sizePolicy().hasHeightForWidth())
        self.long_label.setSizePolicy(sizePolicy)
        self.long_label.setMinimumSize(QtCore.QSize(65, 16))
        self.long_label.setMaximumSize(QtCore.QSize(200, 200))
        self.long_label.setObjectName(_fromUtf8("long_label"))
        self.alt_label = QtGui.QLabel(self.centralWidget)
        self.alt_label.setGeometry(QtCore.QRect(26, 155, 59, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alt_label.sizePolicy().hasHeightForWidth())
        self.alt_label.setSizePolicy(sizePolicy)
        self.alt_label.setMinimumSize(QtCore.QSize(51, 16))
        self.alt_label.setMaximumSize(QtCore.QSize(200, 200))
        self.alt_label.setObjectName(_fromUtf8("alt_label"))
        self.server_info_label = QtGui.QLabel(self.centralWidget)
        self.server_info_label.setGeometry(QtCore.QRect(24, 180, 190, 28))
        self.server_info_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.server_info_label.setFont(font)
        self.server_info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.server_info_label.setWordWrap(False)
        self.server_info_label.setObjectName(_fromUtf8("server_info_label"))
        self.backup_server_url_label = QtGui.QLabel(self.centralWidget)
        self.backup_server_url_label.setGeometry(QtCore.QRect(26, 313, 129, 17))
        self.backup_server_url_label.setMinimumSize(QtCore.QSize(121, 16))
        self.backup_server_url_label.setMaximumSize(QtCore.QSize(200, 200))
        self.backup_server_url_label.setObjectName(_fromUtf8("backup_server_url_label"))
        self.backup_enabled = QtGui.QCheckBox(self.centralWidget)
        self.backup_enabled.setGeometry(QtCore.QRect(300, 312, 131, 22))
        self.backup_enabled.setMinimumSize(QtCore.QSize(119, 20))
        self.backup_enabled.setMaximumSize(QtCore.QSize(200, 200))
        self.backup_enabled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.backup_enabled.setAutoFillBackground(False)
        self.backup_enabled.setAutoRepeatInterval(100)
        self.backup_enabled.setTristate(False)
        self.backup_enabled.setObjectName(_fromUtf8("backup_enabled"))
        self.proxy_status_label = QtGui.QLabel(self.centralWidget)
        self.proxy_status_label.setGeometry(QtCore.QRect(24, 410, 132, 20))
        self.proxy_status_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.proxy_status_label.setFont(font)
        self.proxy_status_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.proxy_status_label.setWordWrap(False)
        self.proxy_status_label.setObjectName(_fromUtf8("proxy_status_label"))
        self.server_label = QtGui.QLabel(self.centralWidget)
        self.server_label.setGeometry(QtCore.QRect(26, 436, 47, 17))
        self.server_label.setMaximumSize(QtCore.QSize(200, 200))
        self.server_label.setObjectName(_fromUtf8("server_label"))
        self.server_status = QtGui.QLabel(self.centralWidget)
        self.server_status.setGeometry(QtCore.QRect(153, 436, 101, 17))
        self.server_status.setMaximumSize(QtCore.QSize(200, 200))
        self.server_status.setObjectName(_fromUtf8("server_status"))
        self.backup_server_label = QtGui.QLabel(self.centralWidget)
        self.backup_server_label.setGeometry(QtCore.QRect(26, 464, 99, 17))
        self.backup_server_label.setMaximumSize(QtCore.QSize(200, 200))
        self.backup_server_label.setObjectName(_fromUtf8("backup_server_label"))
        self.backup_server_status = QtGui.QLabel(self.centralWidget)
        self.backup_server_status.setGeometry(QtCore.QRect(153, 464, 101, 17))
        self.backup_server_status.setMaximumSize(QtCore.QSize(200, 200))
        self.backup_server_status.setObjectName(_fromUtf8("backup_server_status"))
        self.port1_label = QtGui.QLabel(self.centralWidget)
        self.port1_label.setGeometry(QtCore.QRect(26, 492, 45, 17))
        self.port1_label.setMaximumSize(QtCore.QSize(200, 200))
        self.port1_label.setObjectName(_fromUtf8("port1_label"))
        self.port1_status = QtGui.QLabel(self.centralWidget)
        self.port1_status.setGeometry(QtCore.QRect(153, 492, 101, 17))
        self.port1_status.setMaximumSize(QtCore.QSize(200, 200))
        self.port1_status.setObjectName(_fromUtf8("port1_status"))
        self.port2_status = QtGui.QLabel(self.centralWidget)
        self.port2_status.setGeometry(QtCore.QRect(153, 520, 101, 17))
        self.port2_status.setMaximumSize(QtCore.QSize(200, 200))
        self.port2_status.setObjectName(_fromUtf8("port2_status"))
        self.port2_label = QtGui.QLabel(self.centralWidget)
        self.port2_label.setGeometry(QtCore.QRect(26, 520, 45, 17))
        self.port2_label.setMaximumSize(QtCore.QSize(200, 200))
        self.port2_label.setObjectName(_fromUtf8("port2_label"))
        self.port3_label = QtGui.QLabel(self.centralWidget)
        self.port3_label.setGeometry(QtCore.QRect(26, 548, 45, 17))
        self.port3_label.setMaximumSize(QtCore.QSize(200, 200))
        self.port3_label.setObjectName(_fromUtf8("port3_label"))
        self.port3_status = QtGui.QLabel(self.centralWidget)
        self.port3_status.setGeometry(QtCore.QRect(153, 548, 101, 17))
        self.port3_status.setMaximumSize(QtCore.QSize(200, 200))
        self.port3_status.setObjectName(_fromUtf8("port3_status"))
        self.port4_status = QtGui.QLabel(self.centralWidget)
        self.port4_status.setGeometry(QtCore.QRect(153, 576, 101, 17))
        self.port4_status.setMaximumSize(QtCore.QSize(200, 200))
        self.port4_status.setObjectName(_fromUtf8("port4_status"))
        self.port4_label = QtGui.QLabel(self.centralWidget)
        self.port4_label.setGeometry(QtCore.QRect(26, 576, 45, 17))
        self.port4_label.setMaximumSize(QtCore.QSize(200, 200))
        self.port4_label.setObjectName(_fromUtf8("port4_label"))
        self.port5_label = QtGui.QLabel(self.centralWidget)
        self.port5_label.setGeometry(QtCore.QRect(26, 604, 45, 17))
        self.port5_label.setMaximumSize(QtCore.QSize(200, 200))
        self.port5_label.setObjectName(_fromUtf8("port5_label"))
        self.port5_status = QtGui.QLabel(self.centralWidget)
        self.port5_status.setGeometry(QtCore.QRect(153, 604, 101, 17))
        self.port5_status.setMaximumSize(QtCore.QSize(200, 200))
        self.port5_status.setObjectName(_fromUtf8("port5_status"))
        self.orbit_label = QtGui.QLabel(self.centralWidget)
        self.orbit_label.setGeometry(QtCore.QRect(24, 340, 131, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(97)
        sizePolicy.setVerticalStretch(16)
        sizePolicy.setHeightForWidth(self.orbit_label.sizePolicy().hasHeightForWidth())
        self.orbit_label.setSizePolicy(sizePolicy)
        self.orbit_label.setMinimumSize(QtCore.QSize(97, 16))
        self.orbit_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.orbit_label.setFont(font)
        self.orbit_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.orbit_label.setWordWrap(False)
        self.orbit_label.setObjectName(_fromUtf8("orbit_label"))
        self.tle_url_label = QtGui.QLabel(self.centralWidget)
        self.tle_url_label.setGeometry(QtCore.QRect(27, 368, 59, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tle_url_label.sizePolicy().hasHeightForWidth())
        self.tle_url_label.setSizePolicy(sizePolicy)
        self.tle_url_label.setMinimumSize(QtCore.QSize(0, 0))
        self.tle_url_label.setMaximumSize(QtCore.QSize(200, 200))
        self.tle_url_label.setObjectName(_fromUtf8("tle_url_label"))
        self.update_button = QtGui.QPushButton(self.centralWidget)
        self.update_button.setGeometry(QtCore.QRect(300, 362, 87, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_button.sizePolicy().hasHeightForWidth())
        self.update_button.setSizePolicy(sizePolicy)
        self.update_button.setMinimumSize(QtCore.QSize(87, 32))
        self.update_button.setMaximumSize(QtCore.QSize(87, 32))
        self.update_button.setObjectName(_fromUtf8("update_button"))
        self.port_config_label = QtGui.QLabel(self.centralWidget)
        self.port_config_label.setGeometry(QtCore.QRect(451, 20, 200, 28))
        self.port_config_label.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.port_config_label.setFont(font)
        self.port_config_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.port_config_label.setWordWrap(False)
        self.port_config_label.setObjectName(_fromUtf8("port_config_label"))
        self.log_text = QtGui.QTextEdit(self.centralWidget)
        self.log_text.setGeometry(QtCore.QRect(460, 222, 536, 300))
        self.log_text.setMinimumSize(QtCore.QSize(536, 300))
        self.log_text.setMaximumSize(QtCore.QSize(536, 300))
        self.log_text.setReadOnly(True)
        self.log_text.setObjectName(_fromUtf8("log_text"))
        self.save_config_button = QtGui.QPushButton(self.centralWidget)
        self.save_config_button.setGeometry(QtCore.QRect(587, 535, 135, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_config_button.sizePolicy().hasHeightForWidth())
        self.save_config_button.setSizePolicy(sizePolicy)
        self.save_config_button.setMinimumSize(QtCore.QSize(135, 32))
        self.save_config_button.setMaximumSize(QtCore.QSize(135, 32))
        self.save_config_button.setObjectName(_fromUtf8("save_config_button"))
        self.start_proxy_button = QtGui.QPushButton(self.centralWidget)
        self.start_proxy_button.setGeometry(QtCore.QRect(448, 535, 135, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_proxy_button.sizePolicy().hasHeightForWidth())
        self.start_proxy_button.setSizePolicy(sizePolicy)
        self.start_proxy_button.setMinimumSize(QtCore.QSize(135, 32))
        self.start_proxy_button.setMaximumSize(QtCore.QSize(135, 32))
        self.start_proxy_button.setObjectName(_fromUtf8("start_proxy_button"))
        self.exit_button = QtGui.QPushButton(self.centralWidget)
        self.exit_button.setGeometry(QtCore.QRect(867, 535, 135, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_button.sizePolicy().hasHeightForWidth())
        self.exit_button.setSizePolicy(sizePolicy)
        self.exit_button.setMinimumSize(QtCore.QSize(135, 32))
        self.exit_button.setMaximumSize(QtCore.QSize(135, 32))
        self.exit_button.setObjectName(_fromUtf8("exit_button"))
        self.name_text = QtGui.QLineEdit(self.centralWidget)
        self.name_text.setGeometry(QtCore.QRect(160, 47, 128, 23))
        self.name_text.setMinimumSize(QtCore.QSize(128, 23))
        self.name_text.setMaximumSize(QtCore.QSize(128, 23))
        self.name_text.setMaxLength(15)
        self.name_text.setObjectName(_fromUtf8("name_text"))
        self.lat_text = QtGui.QLineEdit(self.centralWidget)
        self.lat_text.setGeometry(QtCore.QRect(160, 82, 128, 23))
        self.lat_text.setMinimumSize(QtCore.QSize(128, 23))
        self.lat_text.setMaximumSize(QtCore.QSize(128, 23))
        self.lat_text.setMaxLength(15)
        self.lat_text.setEchoMode(QtGui.QLineEdit.Normal)
        self.lat_text.setObjectName(_fromUtf8("lat_text"))
        self.long_text = QtGui.QLineEdit(self.centralWidget)
        self.long_text.setGeometry(QtCore.QRect(160, 117, 128, 23))
        self.long_text.setMinimumSize(QtCore.QSize(128, 23))
        self.long_text.setMaximumSize(QtCore.QSize(128, 23))
        self.long_text.setMaxLength(15)
        self.long_text.setObjectName(_fromUtf8("long_text"))
        self.alt_text = QtGui.QLineEdit(self.centralWidget)
        self.alt_text.setGeometry(QtCore.QRect(160, 152, 128, 23))
        self.alt_text.setMinimumSize(QtCore.QSize(128, 23))
        self.alt_text.setMaximumSize(QtCore.QSize(128, 23))
        self.alt_text.setMaxLength(15)
        self.alt_text.setObjectName(_fromUtf8("alt_text"))
        self.backup_server_url_text = QtGui.QLineEdit(self.centralWidget)
        self.backup_server_url_text.setGeometry(QtCore.QRect(160, 310, 128, 23))
        self.backup_server_url_text.setMinimumSize(QtCore.QSize(128, 23))
        self.backup_server_url_text.setMaximumSize(QtCore.QSize(128, 23))
        self.backup_server_url_text.setMaxLength(128)
        self.backup_server_url_text.setObjectName(_fromUtf8("backup_server_url_text"))
        self.tle_url_text = QtGui.QLineEdit(self.centralWidget)
        self.tle_url_text.setGeometry(QtCore.QRect(160, 365, 128, 23))
        self.tle_url_text.setMinimumSize(QtCore.QSize(128, 23))
        self.tle_url_text.setMaximumSize(QtCore.QSize(128, 23))
        self.tle_url_text.setMaxLength(128)
        self.tle_url_text.setObjectName(_fromUtf8("tle_url_text"))
        self.about_button = QtGui.QPushButton(self.centralWidget)
        self.about_button.setGeometry(QtCore.QRect(726, 535, 135, 32))
        self.about_button.setMinimumSize(QtCore.QSize(135, 32))
        self.about_button.setMaximumSize(QtCore.QSize(135, 32))
        self.about_button.setObjectName(_fromUtf8("about_button"))
        self.hit_logo = QtGui.QPushButton(self.centralWidget)
        self.hit_logo.setGeometry(QtCore.QRect(443, 570, 221, 51))
        self.hit_logo.setMinimumSize(QtCore.QSize(221, 51))
        self.hit_logo.setMaximumSize(QtCore.QSize(221, 51))
        self.hit_logo.setStyleSheet(_fromUtf8("background-color:rgb(232, 232, 232);\n"
"border: none"))
        self.hit_logo.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("logo/hit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hit_logo.setIcon(icon)
        self.hit_logo.setIconSize(QtCore.QSize(221, 51))
        self.hit_logo.setObjectName(_fromUtf8("hit_logo"))
        self.by2hit_logo = QtGui.QPushButton(self.centralWidget)
        self.by2hit_logo.setGeometry(QtCore.QRect(680, 570, 147, 51))
        self.by2hit_logo.setMinimumSize(QtCore.QSize(147, 51))
        self.by2hit_logo.setMaximumSize(QtCore.QSize(147, 51))
        self.by2hit_logo.setStyleSheet(_fromUtf8("background-color:rgb(232, 232, 232);\n"
"border: none"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("logo/by2hit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.by2hit_logo.setIcon(icon1)
        self.by2hit_logo.setIconSize(QtCore.QSize(147, 51))
        self.by2hit_logo.setObjectName(_fromUtf8("by2hit_logo"))
        self.lilacsat_logo = QtGui.QPushButton(self.centralWidget)
        self.lilacsat_logo.setGeometry(QtCore.QRect(850, 570, 150, 51))
        self.lilacsat_logo.setMinimumSize(QtCore.QSize(150, 51))
        self.lilacsat_logo.setMaximumSize(QtCore.QSize(150, 51))
        self.lilacsat_logo.setStyleSheet(_fromUtf8("background-color:rgb(232, 232, 232);\n"
"border: none"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("logo/lilacsat.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lilacsat_logo.setIcon(icon2)
        self.lilacsat_logo.setIconSize(QtCore.QSize(150, 51))
        self.lilacsat_logo.setObjectName(_fromUtf8("lilacsat_logo"))
        self.server_list = QtGui.QListWidget(self.centralWidget)
        self.server_list.setGeometry(QtCore.QRect(30, 230, 261, 71))
        self.server_list.setObjectName(_fromUtf8("server_list"))
        self.eg_of_server_info = QtGui.QLabel(self.centralWidget)
        self.eg_of_server_info.setGeometry(QtCore.QRect(50, 210, 231, 21))
        self.eg_of_server_info.setMinimumSize(QtCore.QSize(121, 16))
        self.eg_of_server_info.setMaximumSize(QtCore.QSize(300, 200))
        self.eg_of_server_info.setObjectName(_fromUtf8("eg_of_server_info"))
        self.new_server = QtGui.QPushButton(self.centralWidget)
        self.new_server.setGeometry(QtCore.QRect(310, 230, 97, 26))
        self.new_server.setObjectName(_fromUtf8("new_server"))
        self.del_server = QtGui.QPushButton(self.centralWidget)
        self.del_server.setGeometry(QtCore.QRect(310, 270, 97, 26))
        self.del_server.setObjectName(_fromUtf8("del_server"))
        self.port_list = QtGui.QTableWidget(self.centralWidget)
        self.port_list.setGeometry(QtCore.QRect(460, 50, 536, 171))
        self.port_list.setObjectName(_fromUtf8("port_list"))
        self.port_list.setColumnCount(0)
        self.port_list.setRowCount(0)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1016, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Mun Downlink Proxy", None))
        self.user_info_label.setText(_translate("MainWindow", "User Information", None))
        self.name_label.setText(_translate("MainWindow", "Nick Name:", None))
        self.lat_label.setText(_translate("MainWindow", "Latitiude:", None))
        self.long_label.setText(_translate("MainWindow", "Longitude:", None))
        self.alt_label.setText(_translate("MainWindow", "Altitude:", None))
        self.server_info_label.setText(_translate("MainWindow", "Server Information", None))
        self.backup_server_url_label.setText(_translate("MainWindow", "Backup Server URL:", None))
        self.backup_enabled.setText(_translate("MainWindow", "Enable Backup:", None))
        self.proxy_status_label.setText(_translate("MainWindow", "Proxy Status", None))
        self.server_label.setText(_translate("MainWindow", "Server:", None))
        self.server_status.setText(_translate("MainWindow", "Not Connected", None))
        self.backup_server_label.setText(_translate("MainWindow", "Backup Server:", None))
        self.backup_server_status.setText(_translate("MainWindow", "Not Connected", None))
        self.port1_label.setText(_translate("MainWindow", "Port 1:", None))
        self.port1_status.setText(_translate("MainWindow", "Not Connected", None))
        self.port2_status.setText(_translate("MainWindow", "Not Connected", None))
        self.port2_label.setText(_translate("MainWindow", "Port 2:", None))
        self.port3_label.setText(_translate("MainWindow", "Port 3:", None))
        self.port3_status.setText(_translate("MainWindow", "Not Connected", None))
        self.port4_status.setText(_translate("MainWindow", "Not Connected", None))
        self.port4_label.setText(_translate("MainWindow", "Port 4:", None))
        self.port5_label.setText(_translate("MainWindow", "Port 5:", None))
        self.port5_status.setText(_translate("MainWindow", "Not Connected", None))
        self.orbit_label.setText(_translate("MainWindow", "Orbit Update", None))
        self.tle_url_label.setText(_translate("MainWindow", "TLE URL:", None))
        self.update_button.setText(_translate("MainWindow", "Update", None))
        self.port_config_label.setText(_translate("MainWindow", "Port Configurations", None))
        self.save_config_button.setText(_translate("MainWindow", "Save Configure", None))
        self.start_proxy_button.setText(_translate("MainWindow", "Start Proxy", None))
        self.exit_button.setText(_translate("MainWindow", "Exit", None))
        self.about_button.setText(_translate("MainWindow", "About", None))
        self.eg_of_server_info.setText(_translate("MainWindow", "e.g.   server_name----->host:port", None))
        self.new_server.setText(_translate("MainWindow", "New", None))
        self.del_server.setText(_translate("MainWindow", "Delete", None))

