/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(angle_cf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e71d88fc9cd5b5892655ffebb69cf4db)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/angle_cf.h>
// pydoc.h is automatically generated in the build directory
#include <angle_cf_pydoc.h>

void bind_angle_cf(py::module& m) {

    using angle_cf = gr::lilacsat::angle_cf;


    py::class_<angle_cf, gr::block, gr::basic_block, std::shared_ptr<angle_cf>>(
        m, "angle_cf", D(angle_cf))

        .def(py::init(&angle_cf::make), D(angle_cf, make))


        ;
}
