/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(attach_rs_codeblock.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4c3c270c191e0c563f36bf4ff052a52b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/attach_rs_codeblock.h>
// pydoc.h is automatically generated in the build directory
#include <attach_rs_codeblock_pydoc.h>

void bind_attach_rs_codeblock(py::module& m)
{

    using attach_rs_codeblock    = gr::lilacsat::attach_rs_codeblock;


    py::class_<attach_rs_codeblock, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<attach_rs_codeblock>>(m, "attach_rs_codeblock", D(attach_rs_codeblock))

        .def(py::init(&attach_rs_codeblock::make),
           D(attach_rs_codeblock,make)
        )
        



        ;




}








