/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cc_decode_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e54791fe7d600612b375905599b709bc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/cc_decode_bb.h>
// pydoc.h is automatically generated in the build directory
#include <cc_decode_bb_pydoc.h>

void bind_cc_decode_bb(py::module& m)
{

    using cc_decode_bb    = gr::lilacsat::cc_decode_bb;


    py::class_<cc_decode_bb, gr::block, gr::basic_block,
        std::shared_ptr<cc_decode_bb>>(m, "cc_decode_bb", D(cc_decode_bb))

        .def(py::init(&cc_decode_bb::make),
           D(cc_decode_bb,make)
        )
        



        ;




}








