/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ccsds_afsk_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fd7ad672f3c719a11fce96b0ed9a533b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/ccsds_afsk_decode.h>
// pydoc.h is automatically generated in the build directory
#include <ccsds_afsk_decode_pydoc.h>

void bind_ccsds_afsk_decode(py::module& m)
{

    using ccsds_afsk_decode    = gr::lilacsat::ccsds_afsk_decode;


    py::class_<ccsds_afsk_decode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ccsds_afsk_decode>>(m, "ccsds_afsk_decode", D(ccsds_afsk_decode))

        .def(py::init(&ccsds_afsk_decode::make),
           D(ccsds_afsk_decode,make)
        )
        



        ;




}








