/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ccsds_afsk_encode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d0d3582a4ce071cbe7707b22cb519f1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/ccsds_afsk_encode.h>
// pydoc.h is automatically generated in the build directory
#include <ccsds_afsk_encode_pydoc.h>

void bind_ccsds_afsk_encode(py::module& m)
{

    using ccsds_afsk_encode    = gr::lilacsat::ccsds_afsk_encode;


    py::class_<ccsds_afsk_encode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ccsds_afsk_encode>>(m, "ccsds_afsk_encode", D(ccsds_afsk_encode))

        .def(py::init(&ccsds_afsk_encode::make),
           D(ccsds_afsk_encode,make)
        )
        



        ;




}








