/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(codec2_decode_bf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(db9a52e9b6be5cde2742848dcd6b2e7c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/codec2_decode_bf.h>
// pydoc.h is automatically generated in the build directory
#include <codec2_decode_bf_pydoc.h>

void bind_codec2_decode_bf(py::module& m)
{

    using codec2_decode_bf    = gr::lilacsat::codec2_decode_bf;


    py::class_<codec2_decode_bf, gr::sync_interpolator,
        std::shared_ptr<codec2_decode_bf>>(m, "codec2_decode_bf", D(codec2_decode_bf))

        .def(py::init(&codec2_decode_bf::make),
           D(codec2_decode_bf,make)
        )
        



        ;




}








