/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dslwp_tm_parser.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e99de76b39648daecd8db8ff5c41a357)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/dslwp_tm_parser.h>
// pydoc.h is automatically generated in the build directory
#include <dslwp_tm_parser_pydoc.h>

void bind_dslwp_tm_parser(py::module& m)
{

    using dslwp_tm_parser    = gr::lilacsat::dslwp_tm_parser;


    py::class_<dslwp_tm_parser, gr::block, gr::basic_block,
        std::shared_ptr<dslwp_tm_parser>>(m, "dslwp_tm_parser", D(dslwp_tm_parser))

        .def(py::init(&dslwp_tm_parser::make),
           D(dslwp_tm_parser,make)
        )
        



        ;




}








