/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(encode27_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0e59617f68f125b47180c5eb22cc3b15)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/encode27_bb.h>
// pydoc.h is automatically generated in the build directory
#include <encode27_bb_pydoc.h>

void bind_encode27_bb(py::module& m)
{

    using encode27_bb    = gr::lilacsat::encode27_bb;


    py::class_<encode27_bb, gr::sync_interpolator,
        std::shared_ptr<encode27_bb>>(m, "encode27_bb", D(encode27_bb))

        .def(py::init(&encode27_bb::make),
           D(encode27_bb,make)
        )
        



        ;




}








