/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fec_encode_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0faa7ca7d34b168cda2eb086f92ed682)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/fec_encode_b.h>
// pydoc.h is automatically generated in the build directory
#include <fec_encode_b_pydoc.h>

void bind_fec_encode_b(py::module& m)
{

    using fec_encode_b    = gr::lilacsat::fec_encode_b;


    py::class_<fec_encode_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fec_encode_b>>(m, "fec_encode_b", D(fec_encode_b))

        .def(py::init(&fec_encode_b::make),
           D(fec_encode_b,make)
        )
        



        ;




}








