/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(lilacsat1_frame_depack.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0fe5777a756cb2b51213ca720d2cbc0b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/lilacsat1_frame_depack.h>
// pydoc.h is automatically generated in the build directory
#include <lilacsat1_frame_depack_pydoc.h>

void bind_lilacsat1_frame_depack(py::module& m)
{

    using lilacsat1_frame_depack    = gr::lilacsat::lilacsat1_frame_depack;


    py::class_<lilacsat1_frame_depack, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<lilacsat1_frame_depack>>(m, "lilacsat1_frame_depack", D(lilacsat1_frame_depack))

        .def(py::init(&lilacsat1_frame_depack::make),
           D(lilacsat1_frame_depack,make)
        )
        



        ;




}








