/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pdu_f32_to_u8.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c6813cb535eebdae7b529031ad71fd6b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/pdu_f32_to_u8.h>
// pydoc.h is automatically generated in the build directory
#include <pdu_f32_to_u8_pydoc.h>

void bind_pdu_f32_to_u8(py::module& m)
{

    using pdu_f32_to_u8    = gr::lilacsat::pdu_f32_to_u8;


    py::class_<pdu_f32_to_u8, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pdu_f32_to_u8>>(m, "pdu_f32_to_u8", D(pdu_f32_to_u8))

        .def(py::init(&pdu_f32_to_u8::make),
           D(pdu_f32_to_u8,make)
        )
        



        ;




}








