/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(send_file_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f2f3bd460c0e3229573d44cecb70460d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/send_file_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <send_file_pdu_pydoc.h>

void bind_send_file_pdu(py::module& m)
{

    using send_file_pdu    = gr::lilacsat::send_file_pdu;


    py::class_<send_file_pdu, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<send_file_pdu>>(m, "send_file_pdu", D(send_file_pdu))

        .def(py::init(&send_file_pdu::make),
           D(send_file_pdu,make)
        )
        



        ;




}








