/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(serial_sink_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(37a924ce121e712eee2661b0f2fe52c2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/serial_sink_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <serial_sink_pdu_pydoc.h>

void bind_serial_sink_pdu(py::module& m)
{

    using serial_sink_pdu    = gr::lilacsat::serial_sink_pdu;


    py::class_<serial_sink_pdu, gr::block, gr::basic_block,
        std::shared_ptr<serial_sink_pdu>>(m, "serial_sink_pdu", D(serial_sink_pdu))

        .def(py::init(&serial_sink_pdu::make),
           D(serial_sink_pdu,make)
        )
        



        ;




}








