/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sync_det_b.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d508d41be2d7ee927536e9f7e113eb76)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/sync_det_b.h>
// pydoc.h is automatically generated in the build directory
#include <sync_det_b_pydoc.h>

void bind_sync_det_b(py::module& m)
{

    using sync_det_b    = gr::lilacsat::sync_det_b;


    py::class_<sync_det_b, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<sync_det_b>>(m, "sync_det_b", D(sync_det_b))

        .def(py::init(&sync_det_b::make),
           D(sync_det_b,make)
        )
        



        ;




}








