/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(two_bit_dpd_frame_recovery.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(21cdf594deae8ce58ce40c654444666a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/two_bit_dpd_frame_recovery.h>
// pydoc.h is automatically generated in the build directory
#include <two_bit_dpd_frame_recovery_pydoc.h>

void bind_two_bit_dpd_frame_recovery(py::module& m)
{

    using two_bit_dpd_frame_recovery    = gr::lilacsat::two_bit_dpd_frame_recovery;


    py::class_<two_bit_dpd_frame_recovery, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<two_bit_dpd_frame_recovery>>(m, "two_bit_dpd_frame_recovery", D(two_bit_dpd_frame_recovery))

        .def(py::init(&two_bit_dpd_frame_recovery::make),
           D(two_bit_dpd_frame_recovery,make)
        )
        



        ;




}








