/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vitfilt27_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fd19f3613e97a59d8c68f22bd86bc1dc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/vitfilt27_bb.h>
// pydoc.h is automatically generated in the build directory
#include <vitfilt27_bb_pydoc.h>

void bind_vitfilt27_bb(py::module& m)
{

    using vitfilt27_bb    = gr::lilacsat::vitfilt27_bb;


    py::class_<vitfilt27_bb, gr::sync_decimator,
        std::shared_ptr<vitfilt27_bb>>(m, "vitfilt27_bb", D(vitfilt27_bb))

        .def(py::init(&vitfilt27_bb::make),
           D(vitfilt27_bb,make)
        )
        



        ;




}








