/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vitfilt27_fb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(216aa2acd65611d0ca43450396e77659)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lilacsat/vitfilt27_fb.h>
// pydoc.h is automatically generated in the build directory
#include <vitfilt27_fb_pydoc.h>

void bind_vitfilt27_fb(py::module& m)
{

    using vitfilt27_fb    = gr::lilacsat::vitfilt27_fb;


    py::class_<vitfilt27_fb, gr::sync_decimator,
        std::shared_ptr<vitfilt27_fb>>(m, "vitfilt27_fb", D(vitfilt27_fb))

        .def(py::init(&vitfilt27_fb::make),
           D(vitfilt27_fb,make)
        )
        



        ;




}








