/*--------------------------------------------------------------------------
 ** This file is autogenerated from config.h.in 
 ** during the cmake configuration of your project. If you need to make changes
 ** edit the original file NOT THIS FILE.
 ** --------------------------------------------------------------------------*/
#ifndef _CONFIGURATION_HEADER_GUARD_H_
#define _CONFIGURATION_HEADER_GUARD_H_

#define SIZEOF_INT 
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_FLOOR    1
#define HAVE_CEIL     1
/* #undef HAVE_MEMSET */
#define HAVE_POW      1
#define HAVE_SQRT     1
#define HAVE_SIN      1
#define HAVE_COS      1
#define HAVE_ATAN2    1
#define HAVE_LOG10    1
#define HAVE_ROUND    1
#define HAVE_GETOPT   1
#endif
